### ISSUE TITLE
9:16 Content Editing

### ISSUE THREAD

**Issue by bjtitus** [tumblr/kanvas-ios#105]
* Restrict Media to 9:16 aspect ratio.
* Align 9:16 media for devices which are taller than this ratio.

Pan/Zoom Android PR w/ discussions an alignment: https://github.com/Automattic/stories-android/pull/649

**Comment by bjtitus** [comment]
After looking at the Android issue for pan/zoom, it looked like the right thing to do was to top align the content. This would leave a large black area at the bottom on some taller devices (this is on an 11 Pro):

<a href="https://user-images.githubusercontent.com/3250/111218930-08448500-859d-11eb-8246-332140eddba9.PNG"><img src="https://user-images.githubusercontent.com/3250/111218930-08448500-859d-11eb-8246-332140eddba9.PNG" width="300"></a>

I looked at a few other options which aren't really much better:

Aligning to the top of the bottom story frame area:
<a href="https://user-images.githubusercontent.com/3250/111220684-1d221800-859f-11eb-9f29-f5f660cd9e82.PNG"><img src="https://user-images.githubusercontent.com/3250/111220684-1d221800-859f-11eb-9f29-f5f660cd9e82.PNG" width="300"></a>

Center alignment:
<a href="https://user-images.githubusercontent.com/3250/111220721-27dcad00-859f-11eb-82a1-a8e205b34551.PNG"><img src="https://user-images.githubusercontent.com/3250/111220721-27dcad00-859f-11eb-82a1-a8e205b34551.PNG" width="300"></a>

**Comment by megsfulton** [comment]
Hm yeah, none of those seem quite right. 

Are you able to align the top of the image to the bottom of the status bar? I'm curious if that might be an option that looks okay?

**Comment by bjtitus** [comment]
I can't align it perfectly but can use the top area layout guide to align it, which includes a bit of extra padding below:

<a href="https://user-images.githubusercontent.com/3250/111254583-fda8e080-85da-11eb-859c-a70add024574.png"><img src="https://user-images.githubusercontent.com/3250/111254583-fda8e080-85da-11eb-859c-a70add024574.png" width="300"></a>

This seems to look good on the largest iPhone 12 Pro Max screen as well:
<a href="https://user-images.githubusercontent.com/3250/111254986-d6064800-85db-11eb-9b14-5b7943173b91.png"><img src="https://user-images.githubusercontent.com/3250/111254986-d6064800-85db-11eb-9b14-5b7943173b91.png" width="300"></a>

**Comment by bjtitus** [comment]
This was merged in iOS 17.2 (https://github.com/wordpress-mobile/WordPress-iOS/pull/16229)
