### ISSUE TITLE
Handling images / video selected from device photos 

### ISSUE THREAD

**Issue by megsfulton** [tumblr/kanvas-ios#3]
Current behavior: 
Both landscape and portrait media is scaled to fit the width of the screen. 

Options for discussion: 
1) Automatically scale the media to fit the full height of the screen for portrait images. Continue scaling to fit the width for landscape. 
2) Allow for manipulation of the background image so user can scale and crop. 
3) Something else?

**Comment by bjtitus** [comment]
This was implemented in the shipped Stories version in WP-iOS.
