### ISSUE TITLE
The permissions screen buttons do not work after revoking manually

### ISSUE THREAD

**Issue by bjtitus** [tumblr/kanvas-ios#55]
- Accept permissions when first using
- Go back to the Privacy screen in settings and disable camera and microphone access
- Go back to create with Kanvas
- The "Allow access to camera/microphone" buttons do not work

We probably need to show better messaging here as I don't think it's possible to enable the in-app after they have been manually disabled.

**Comment by jschementi** [comment]
This should be handled by implementing: https://github.com/tumblr/kanvas-ios/blob/f4d21a03a416d0620dd4abd693fc0f4935cf528d/Classes/Camera/CameraController.swift#L92

If a setting is already set, that method should be called. In the Tumblr app, this method is implemented to navigate you to the Settings app, so you can manually enable whatever settings that are necessary.

**Comment by bjtitus** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/15903
