### ISSUE TITLE
Text object added to one slide shows up on the next slide.

### ISSUE THREAD

**Issue by megsfulton** [tumblr/kanvas-ios#96]
What happened:
- Reordered slides (this is an important step to reproduce) 
- Added text to an image slide
- Tapped on the next slide to add different text and the text from the previous slide persisted 
- Deleting the text from one slide, deleted it from both slides 
- Only those two slides were affected

Video: https://d.pr/v/IJpJDa

Was reproduce-able with in the same story, can see it here: https://meganmesses.wordpress.com/2021/03/04/lapis-ring/

**Comment by aforcier** [comment]
Was able to reproduce (I needed to have text added to a slide and then reorder it).
