### ISSUE TITLE
Crash: Reordering slides

### ISSUE THREAD

**Issue by megsfulton** [tumblr/kanvas-ios#98]
Experienced a crash while reordering slides. Submitted a crash report for it.

**Comment by megsfulton** [comment]
Was able to reproduce this on another 10+slide story reordering slides.

**Comment by aforcier** [comment]
Looks like this crash: https://sentry.io/share/issue/1d1a27992e684388a6f542f7a8a3db38/

**Comment by bjtitus** [comment]
I _think_ this is an iOS crash: https://stackoverflow.com/questions/51553223/handling-multiple-uicollectionview-interactivemovements-crash-uidragsnapping

I've implemented the fix mentioned in that thread, but will test a little further.
